### ISSUE TITLE
Menus are white on white

### ISSUE THREAD

**Issue by fnky** [Fiddle-N/material-incognito-dark-theme#13]
When opening menus from both extensions and Chrome, the background and text color is both white, unless being hovered over.

![Chrome white on white menu](https://user-images.githubusercontent.com/995050/46070269-9e8e5180-c17d-11e8-8dc8-f1078edf1ace.png)

**Comment by GeitHub** [comment]
I'm on Mac also, but I'm not having this problem

**Comment by Fiddle-N** [comment]
@fnky - Themes do not have the power to colour text in the menus, so unless something drastically changed I think this is just a bug with your installation of Chrome. 

@GeitHub - I suggest that you change your username! Because Github email notifications have the username as the subject, the emails I get when you send a comment look like they could be phishing emails at first, since the email subject is Geithub which looks to me like a misspelled GitHub.

**Comment by zeroedin** [comment]
This is a follow up for quite possibly a similar issue..  Seems bookmark folders stay white on white in the dark mode theme.  Is there anyway to make the menu drop down background dark or the folder dark on white?  If not, cheers to you for the theme anyways!

https://www.dropbox.com/s/evtciqe1qzvwoyf/Screenshot%202018-10-01%2009.28.14.png?dl=0
