### ISSUE TITLE
After update to version 81.0.4044.43 address bar background is white

### ISSUE THREAD

**Issue by DoCode** [Fiddle-N/material-incognito-dark-theme#21]
After the update to version 81.0.4044.43 the address bar background is white.
I think it's related to [this commit](https://chromium.googlesource.com/chromium/src/+/b4a79ea83cb750506b05e26d69b9705da6065f3e).

**Comment by Fiddle-N** [comment]
Previously, it seems that the omnibox colour was derived from the toolbar colour, but the theme author could override if they wanted to. Pretty much no one has overriden, because almost no one knew you could do so!

Now it seems that they've removed the ability to derive the colour from the toolbar, but overriding is still possible. So I'm updating my own themes to override the omnibox colour for now.

**Comment by Fiddle-N** [comment]
By the way, you should probably just uninstall my theme anyway :) The official dark theme has been implemented for a while; my theme has been superseded by that for months. I'll make the update, but I suggest just uninstalling the theme regardless.

**Comment by Fiddle-N** [comment]
Alright, the theme has been updated. For reasons only Google Chrome knows, themes need **reviewing** before they can be released to production. Really weird. But once the RGB colours in my JSON have been reviewed and approved to ensure they contain no malware in them, you should see the change appear automatically in your browser.
