### ISSUE TITLE
divider line too white now, + new tabs aren't dark.

### ISSUE THREAD

**Issue by ANaPhOrAX** [Fiddle-N/material-incognito-dark-theme#22]
Hey, so New Tabs aren't dark anymore. Used to be where if I opened chrome, or had chrome open already and clicked New Tab, I'd get a blank page, dark, with some pinned sites. But now it's white, same icons, but no captions (or not readable because the text is white too, I'm not sure. I tried selecting the text but I couldn't, so the captions are probably just gone).

Other than that, the divider line between menu/bookmarks and page is now waaaay too bright. Super in-your-face. Here's a screenshot of what I mean. Please do look at the image in full resolution, because for some reason, if you don't, the divider line looks more like a gray, when in actuality it's white. https://i.imgur.com/qLv07EN.png

edit: interestingly, if I drag away one tab to separate it from the rest, the annoying white divider line disappears. ONLY from _that_ separated tab, however. So it does seem to be a bug. I also tried seeing if bookmarks bar disabled/enabled during startup made a difference, but it doesn't. It does seem to be a thing related to the broken white blank page.

No addons enabled btw.

**Comment by Fiddle-N** [comment]
Hi,

Thanks for your bug report. Unfortunately, I cannot reproduce any of the issues that you are seeing. This is what I see when I have the theme installed.

![image](https://user-images.githubusercontent.com/20640528/88459628-ab218500-ce8e-11ea-9d96-b83d217be20c.png)

A theme's appearance can often change from time to time even if the developer hasn't made any changes - this is because the Chrome dev team often change how the theme's file are interpreted. Sometimes this can introduce bugs, which may explain what you are seeing on your device. In any case, I would not recommend you use this theme for this reason. This particular theme has long been superseded by the official Chrome dark mode, and I recommend you use that instead as it will be more reliable and will colour context and Settings menu as well.
